### ISSUE TITLE
Import BEL named complexes into BE namespace and relations

### ISSUE THREAD

**Issue by bgyori** [sorgerlab/bioentities#10]
Here is a list of BEL named complexes and their members:
[complex_table.txt](https://github.com/sorgerlab/bioentities/files/505112/complex_table.txt)
based on
http://resource.belframework.org/belframework/1.0/resource/named-complexes.xbel

**Comment by johnbachman** [comment]
Added in f8d49d6e89d.

**Comment by johnbachman** [comment]
Whoops--thought this was about families, not complexes. Deleting previous commit ref.

**Comment by bgyori** [comment]
Done in #12
