### ISSUE TITLE
Confused about all the forks

### ISSUE THREAD

**Issue by hickst** [sorgerlab/bioentities#13]
There seem to be at least 3 forks of this project: sorgerlab, johnbackman, and bgyori. And now I've forked and may have added a pull request from the wrong fork. Which one should I use as the base repository for incorporating data into Reach?

**Comment by bgyori** [comment]
Hi Tom, it would be best to fork sorgerlab/bioentities, submit pull requests here, and treat it as the official one.

**Comment by hickst** [comment]
OK, will do...thanks.
